apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of a Let's Encrypt Certificate to manage."
metadata:
  name: "certificate.stable.k8s.psg.io"
versions:
  - name: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-cert-manager
  name: kube-cert-manager
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: rosskukulinski/kube-cert-manager:0.5.0
          args:
            - "-data-dir=/var/lib/cert-manager"
            #- "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
            # NOTE: the URL above points to the staging server, where you won't get real certs.
            # Uncomment the line below to use the production LetsEncrypt server:
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            # You can run multiple instances of kube-cert-manager for the same namespace(s), 
            # each watching for a different value for the 'class' label
            #- "-class=default"
            # You can choose to monitor only some namespaces, otherwise all namespaces will be monitored
            #- "-namespaces=default,test"
            # If you set a default email, you can omit the field/annotation from Certificates/Ingresses
            - "-default-email=zhaw.srueg@mailhero.io"
            # If you set a default provider, you can omit the field/annotation from Certificates/Ingresses
            - "-default-provider=dnsimple"
          env:
            - name: DNSIMPLE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: dnsimple-credentials
                  key: email
            - name: DNSIMPLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dnsimple-credentials
                  key: api_token
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: "data"
          emptyDir: {}