apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /kubernetes/registry
    server: 172.21.21.201