# 1. install python on target hosts
# 2. run playbook: ansible-playbook -i hosts basic_setup.yml -K --extra-vars "DNSimpleToken=TOKEN"
---
- hosts: linux
  become: true
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes

    - name: Install required packages for hyper-v
      apt: name={{item}} state=installed
      with_items:
        - linux-virtual-lts-xenial
        - linux-tools-virtual-lts-xenial
        - linux-cloud-tools-virtual-lts-xenial

    - name: Set hostname
      hostname: name={{ inventory_hostname }}
      when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

    - name: Copy dDNS script
      copy:
        src: files/ddns.sh
        dest: /usr/bin/ddns.sh
        owner: root
        group: root
        mode: "u+x"

    - name: Setup dDNS crontab
      cron:
        name: "Set dDNS"
        minute: "*"
        job: "export DNSimpleToken={{ DNSimpleToken }} DNSimpleRecordID={{ dns_record_id }}; ddns.sh >> /var/log/ddns.log 2>&1"
